export const EXPENSE_CATEGORIES = [
  "Makanan & Minuman", "Transportasi", "Belanja Bulanan", "Tagihan & Utilitas",
  "Hiburan & Rekreasi", "Kesehatan & Obat", "Pendidikan", 
  "Piutang (Memberi Pinjaman)", 
  "Membayar Utang (Cicilan/Lunas)", 
  "Cicilan & Denda", "Lainnya"
];

export const INCOME_CATEGORIES = [
  "Gaji & Upah", "Bonus & Tunjangan", "Hasil Usaha", "Investasi & Dividen",
  "Utang (Menerima Pinjaman)", 
  "Pengembalian Piutang (Utang Dibayar)", 
  "Hadiah & Hibah", "Penjualan Aset", "Pencairan Dana", "Lainnya"
];

export const CATEGORY_COLORS: Record<string, string> = {
  // Expense
  "Makanan & Minuman": "#F87171", 
  "Transportasi": "#FB923C", 
  "Belanja Bulanan": "#FBBF24", 
  "Tagihan & Utilitas": "#34D399", 
  "Hiburan & Rekreasi": "#60A5FA", 
  "Kesehatan & Obat": "#818CF8", 
  "Pendidikan": "#A78BFA", 
  "Piutang (Memberi Pinjaman)": "#F472B6", 
  "Membayar Utang (Cicilan/Lunas)": "#FB7185", 
  "Cicilan & Denda": "#9CA3AF", 
  // Income
  "Gaji & Upah": "#4ADE80", 
  "Bonus & Tunjangan": "#2DD4BF", 
  "Hasil Usaha": "#22D3EE", 
  "Investasi & Dividen": "#38BDF8", 
  "Utang (Menerima Pinjaman)": "#A3E635", 
  "Pengembalian Piutang (Utang Dibayar)": "#FACC15", 
  "Hadiah & Hibah": "#FDA4AF",
  "Penjualan Aset": "#94A3B8",
  "Pencairan Dana": "#C084FC",
  "Lainnya": "#CBD5E1"
};

export const TRANSLATIONS = {
  id: {
    dashboard: "Beranda",
    reports: "Laporan",
    settings: "Pengaturan",
    help: "Bantuan",
    hello: "Hai",
    skyText: "Langit cerah untuk hari yang cerah di bulan",
    skyTextDark: "Malam yang tenang di bulan",
    totalBalance: "Saldo Utama",
    netCashflow: "Flowcash",
    income: "Pemasukan",
    expense: "Pengeluaran",
    totalDebt: "Total Saya Berhutang",
    unpaidDebt: "Sisa Utang",
    totalLent: "Total Saya Pinjamkan",
    unpaidLent: "Belum Kembali",
    recentActivity: "Riwayat Transaksi",
    newRecord: "Tambah",
    delete: "Hapus",
    noTransaction: "Belum ada transaksi bulan ini",
    startRecord: "Mulai catat perjalanan keuanganmu!",
    backToFolder: "Kembali",
    accountingLedger: "Buku Besar",
    period: "Periode",
    date: "Tanggal",
    category: "Kategori",
    note: "Catatan",
    in: "Masuk",
    out: "Keluar",
    balance: "Sisa",
    monthlyArchive: "Arsip Bulanan",
    openData: "Lihat",
    emptyArchive: "Belum Ada Data",
    noDataSaved: "Data transaksi lama akan muncul di sini.",
    newTransaction: "Transaksi Baru",
    save: "Simpan Transaksi",
    amount: "Nominal (Rp)",
    descPlaceholder: "Cth: Kopi Kenangan...",
    optional: "Opsional",
    typeExpense: "Keluar",
    typeIncome: "Masuk",
    appearance: "Tampilan",
    profile: "Identitas",
    language: "Bahasa",
    yourName: "Nama Kamu",
    greetingMessage: "Pesan Sambutan",
    themeLight: "Langit Pagi (Terang)",
    themeDark: "Luar Angkasa (Gelap)",
    tutorialTitle: "Panduan Singkat",
    tut1Title: "Mencatat",
    tut1Desc: "Tekan tombol (+) melayang. Pilih kategori 'Utang' jika meminjam, dan 'Membayar Utang' saat melunasi.",
    tut2Title: "Analisa",
    tut2Desc: "Menu Laporan menyimpan semua riwayat bulananmu secara otomatis dan rapi.",
    tut3Title: "Personalisasi",
    tut3Desc: "Ubah nama dan tema sesuai suasana hatimu di menu Pengaturan.",
    totalFinal: "Total Akhir",
    navDescDashboard: "Ringkasan saldo & utang",
    navDescReports: "Arsip buku besar",
    navDescSettings: "Ubah profil & tema",
    navDescHelp: "Bantuan penggunaan",
    chartTitle: "Analisis Grafik",
    chartPie: "Lingkaran",
    chartBar: "Batang",
    filterAll: "Gabungan",
    filterIn: "Masuk",
    filterOut: "Keluar",
    yearView: "1 Tahun",
    monthView: "Bulanan",
    openingBalance: "Saldo Awal"
  },
  en: {
    dashboard: "Home",
    reports: "Reports",
    settings: "Settings",
    help: "Help",
    hello: "Hi",
    skyText: "Clear blue skies for cash flow in",
    skyTextDark: "Stars shining for cash flow in",
    totalBalance: "Main Balance",
    netCashflow: "Flowcash",
    income: "Income",
    expense: "Expense",
    totalDebt: "Total Debt Taken",
    unpaidDebt: "Remaining Debt",
    totalLent: "Total Loans Given",
    unpaidLent: "Not Yet Repaid",
    recentActivity: "Transaction History",
    newRecord: "Add New",
    delete: "Remove",
    noTransaction: "No transactions this month",
    startRecord: "Start tracking your financial journey!",
    backToFolder: "Go Back",
    accountingLedger: "General Ledger",
    period: "Period",
    date: "Date",
    category: "Category",
    note: "Note",
    in: "Credit",
    out: "Debit",
    balance: "Balance",
    monthlyArchive: "Monthly Archive",
    openData: "View",
    emptyArchive: "No Data Yet",
    noDataSaved: "Past transaction data will appear here.",
    newTransaction: "New Transaction",
    save: "Save Record",
    amount: "Amount (Rp)",
    descPlaceholder: "E.g., Starbucks...",
    optional: "Optional",
    typeExpense: "Expense",
    typeIncome: "Income",
    appearance: "Appearance",
    profile: "Identity",
    language: "Language",
    yourName: "Your Name",
    greetingMessage: "Greeting Message",
    themeLight: "Morning Sky (Light)",
    themeDark: "Deep Space (Dark)",
    tutorialTitle: "Quick Guide",
    tut1Title: "Recording",
    tut1Desc: "Press the floating (+) button. Use 'Utang' category when borrowing, 'Membayar Utang' when repaying.",
    tut2Title: "Analysis",
    tut2Desc: "The Reports menu automatically organizes all your monthly history neatly.",
    tut3Title: "Personalize",
    tut3Desc: "Change your name and theme to match your mood in Settings.",
    totalFinal: "Grand Total",
    navDescDashboard: "Balance & debt summary",
    navDescReports: "Ledger archives",
    navDescSettings: "Profile & theme",
    navDescHelp: "Usage guide",
    chartTitle: "Chart Analysis",
    chartPie: "Pie",
    chartBar: "Bar",
    filterAll: "Mixed",
    filterIn: "Income",
    filterOut: "Expense",
    yearView: "1 Year",
    monthView: "Monthly",
    openingBalance: "Opening Balance"
  }
};
